// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rise_Tech_Rehber.Data;

namespace Rise_Tech_Rehber.Data.Migrations
{
    [DbContext(typeof(RehberDbContext))]
    [Migration("20220216180958_Rehber_16022022_2109")]
    partial class Rehber_16022022_2109
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimBilgisi", b =>
                {
                    b.Property<int>("IB_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BilgiIcerigi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IT_ID")
                        .HasColumnType("int");

                    b.Property<int?>("KisiUU_ID")
                        .HasColumnType("int");

                    b.Property<int>("UU_ID")
                        .HasColumnType("int");

                    b.HasKey("IB_ID");

                    b.HasIndex("IT_ID")
                        .IsUnique();

                    b.HasIndex("KisiUU_ID");

                    b.ToTable("ILETISIMBILGILER");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimTip", b =>
                {
                    b.Property<int>("IT_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("TipAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IT_ID");

                    b.ToTable("ILETISIMTIPLER");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.Kisi", b =>
                {
                    b.Property<int>("UU_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UU_ID");

                    b.ToTable("KISILER");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimBilgisi", b =>
                {
                    b.HasOne("Rise_Tech_Rehber.Data.IletisimTip", "IletisimTip")
                        .WithOne("IletisimBilgisi")
                        .HasForeignKey("Rise_Tech_Rehber.Data.IletisimBilgisi", "IT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise_Tech_Rehber.Data.Kisi", null)
                        .WithMany("IletisimBilgileri")
                        .HasForeignKey("KisiUU_ID");

                    b.Navigation("IletisimTip");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimTip", b =>
                {
                    b.Navigation("IletisimBilgisi");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.Kisi", b =>
                {
                    b.Navigation("IletisimBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
