// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Rise_Tech_Rehber.Data;

namespace Rise_Tech_Rehber.Data.Migrations
{
    [DbContext(typeof(RehberDbContext))]
    partial class RehberDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.14")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BilgiIcerigi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IT_ID")
                        .HasColumnType("int");

                    b.Property<int?>("KisiId")
                        .HasColumnType("int");

                    b.Property<bool>("SilinmisMi")
                        .HasColumnType("bit");

                    b.Property<int>("UU_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IT_ID")
                        .IsUnique();

                    b.HasIndex("KisiId");

                    b.ToTable("ILETISIMBILGILER");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimTip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("SilinmisMi")
                        .HasColumnType("bit");

                    b.Property<string>("TipAdı")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ILETISIMTIPLER");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.Kisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Firma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SilinmisMi")
                        .HasColumnType("bit");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KISILER");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimBilgisi", b =>
                {
                    b.HasOne("Rise_Tech_Rehber.Data.IletisimTip", "IletisimTip")
                        .WithOne("IletisimBilgisi")
                        .HasForeignKey("Rise_Tech_Rehber.Data.IletisimBilgisi", "IT_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Rise_Tech_Rehber.Data.Kisi", null)
                        .WithMany("IletisimBilgileri")
                        .HasForeignKey("KisiId");

                    b.Navigation("IletisimTip");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.IletisimTip", b =>
                {
                    b.Navigation("IletisimBilgisi");
                });

            modelBuilder.Entity("Rise_Tech_Rehber.Data.Kisi", b =>
                {
                    b.Navigation("IletisimBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
